onEvent('tags.items', e => {
    e.add('forge:plates/iron', 'tfc:metal/sheet/wrought_iron');
    e.remove('forge:plates/iron', 'create:iron_sheet');
    e.remove('forge:plates/iron', 'immersiveengineering:plate_iron');
})

onEvent('recipes', e => {
    e.replaceInput({}, 'create:brass_ingot', 'tfc:metal/ingot/brass')
    e.replaceInput({}, 'create:silver_ingot', 'tfc:metal/ingot/silver')
    e.replaceInput({}, 'immersiveengineering:ingot_silver', 'tfc:metal/ingot/silver')
    e.replaceInput({}, 'create:bronze_ingot', 'tfc:metal/ingot/bronze')
    e.replaceInput({}, 'immersiveengineering:ingot_bronze', 'tfc:metal/ingot/bronze')
    e.replaceInput({}, 'create:copper_ingot', 'tfc:metal/ingot/copper')
    e.replaceInput({}, 'immersiveengineering:ingot_copper', 'tfc:metal/ingot/copper')
    e.replaceInput({}, 'create:brass_ingot', 'tfc:metal/ingot/brass')
    e.replaceInput({}, 'immersiveengineering:ingot_brass', 'tfc:metal/ingot/brass')
    e.replaceInput({}, 'create:zinc_ingot', 'tfc:metal/ingot/zinc')
    e.replaceInput({}, 'immersiveengineering:ingot_zinc', 'tfc:metal/ingot/zinc')
    e.replaceInput({}, 'create:tin_ingot', 'tfc:metal/ingot/tin')
    e.replaceInput({}, 'immersiveengineering:ingot_tin', 'tfc:metal/ingot/tin')
    e.replaceInput({}, 'create:steel_ingot', 'tfc:metal/ingot/steel')
    e.replaceInput({}, 'immersiveengineering:ingot_steel', 'tfc:metal/ingot/steel')
    e.replaceInput({}, 'create:gold_ingot', 'tfc:metal/ingot/gold')
    e.replaceInput({}, 'immersiveengineering:ingot_gold', 'tfc:metal/ingot/gold')
    e.replaceInput({}, 'create:rose_gold_ingot', 'tfc:metal/ingot/rose_gold')
    e.replaceInput({}, 'immersiveengineering:ingot_rose_gold', 'tfc:metal/ingot/rose_gold')
    e.replaceInput({}, 'create:sterling_silver_ingot', 'tfc:metal/ingot/sterling_silver')
    e.replaceInput({}, 'immersiveengineering:ingot_sterling_silver', 'tfc:metal/ingot/sterling_silver')
    e.replaceInput({}, 'create:nickel_ingot', 'tfc:metal/ingot/nickel')
    e.replaceInput({}, 'immersiveengineering:ingot_nickel', 'tfc:metal/ingot/nickel')
    e.replaceInput({}, 'create:bismuth_ingot', 'tfc:metal/ingot/bismuth')
    e.replaceInput({}, 'immersiveengineering:ingot_bismuth', 'tfc:metal/ingot/bismuth')

    e.replaceOutput({}, 'create:brass_ingot', 'tfc:metal/ingot/brass')
    e.replaceOutput({}, 'create:silver_ingot', 'tfc:metal/ingot/silver')
    e.replaceOutput({}, 'immersiveengineering:ingot_silver', 'tfc:metal/ingot/silver')
    e.replaceOutput({}, 'create:bronze_ingot', 'tfc:metal/ingot/bronze')
    e.replaceOutput({}, 'immersiveengineering:ingot_bronze', 'tfc:metal/ingot/bronze')
    e.replaceOutput({}, 'create:copper_ingot', 'tfc:metal/ingot/copper')
    e.replaceOutput({}, 'immersiveengineering:ingot_copper', 'tfc:metal/ingot/copper')
    e.replaceOutput({}, 'create:brass_ingot', 'tfc:metal/ingot/brass')
    e.replaceOutput({}, 'immersiveengineering:ingot_brass', 'tfc:metal/ingot/brass')
    e.replaceOutput({}, 'create:zinc_ingot', 'tfc:metal/ingot/zinc')
    e.replaceOutput({}, 'immersiveengineering:ingot_zinc', 'tfc:metal/ingot/zinc')
    e.replaceOutput({}, 'create:tin_ingot', 'tfc:metal/ingot/tin')
    e.replaceOutput({}, 'immersiveengineering:ingot_tin', 'tfc:metal/ingot/tin')
    e.replaceOutput({}, 'create:steel_ingot', 'tfc:metal/ingot/steel')
    e.replaceOutput({}, 'immersiveengineering:ingot_steel', 'tfc:metal/ingot/steel')
    e.replaceOutput({}, 'create:gold_ingot', 'tfc:metal/ingot/gold')
    e.replaceOutput({}, 'immersiveengineering:ingot_gold', 'tfc:metal/ingot/gold')
    e.replaceOutput({}, 'create:rose_gold_ingot', 'tfc:metal/ingot/rose_gold')
    e.replaceOutput({}, 'immersiveengineering:ingot_rose_gold', 'tfc:metal/ingot/rose_gold')
    e.replaceOutput({}, 'create:sterling_silver_ingot', 'tfc:metal/ingot/sterling_silver')
    e.replaceOutput({}, 'immersiveengineering:ingot_sterling_silver', 'tfc:metal/ingot/sterling_silver')
    e.replaceOutput({}, 'create:nickel_ingot', 'tfc:metal/ingot/nickel')
    e.replaceOutput({}, 'immersiveengineering:ingot_nickel', 'tfc:metal/ingot/nickel')
    e.replaceOutput({}, 'create:bismuth_ingot', 'tfc:metal/ingot/bismuth')
    e.replaceOutput({}, 'immersiveengineering:ingot_bismuth', 'tfc:metal/ingot/bismuth')


    e.replaceInput({}, 'create:gold_plage', 'tfc:metal/sheet/gold')
    e.replaceInput({}, 'immersiveengineering:plage_gold', 'tfc:metal/sheet/gold')
    e.replaceInput({}, 'create:brass_plage', 'tfc:metal/sheet/brass')
    e.replaceInput({}, 'immersiveengineering:plage_brass', 'tfc:metal/sheet/brass')
    e.replaceInput({}, 'create:copper_plage', 'tfc:metal/sheet/copper')
    e.replaceInput({}, 'immersiveengineering:plage_copper', 'tfc:metal/sheet/copper')

    e.replaceOutput({}, 'create:gold_plage', 'tfc:metal/sheet/gold')
    e.replaceOutput({}, 'immersiveengineering:plage_gold', 'tfc:metal/sheet/gold')
    e.replaceOutput({}, 'create:brass_plage', 'tfc:metal/sheet/brass')
    e.replaceOutput({}, 'immersiveengineering:plage_brass', 'tfc:metal/sheet/brass')
    e.replaceOutput({}, 'create:copper_plage', 'tfc:metal/sheet/copper')
    e.replaceOutput({}, 'immersiveengineering:plage_copper', 'tfc:metal/sheet/copper')
})
